export const parallelsTool = {
  id: "parallels",
  slug: "parallels",
  name: "Parallels Desktop",
  tagline: "Run Windows on Mac without rebooting",
  officialUrl: "https://www.parallels.com/products/desktop/",
  website: "https://prf.hn/click/camref:1101l5KJYo",
  trialUrl: "https://www.parallels.com/products/desktop/trial/",
  buyUrl: "https://www.parallels.com/products/desktop/buy/",
  logo: "/logos/parallels.png",
  categories: [
    "virtualization",
    "mac-productivity",
    "developer-tools",
    "gaming",
  ],
  pricing: [
    {
      name: "Standard Subscription",
      price: 64.99,
      period: "/year",
      features: [
        "8 GB vRAM",
        "4 vCPUs",
        "Run Windows and Windows applications",
        "Use Linux and macOS in a virtual machine",
        "Access Windows Excel features on Mac",
        "Unlimited phone and email support",
      ],
    },
    {
      name: "Standard One-time Purchase",
      price: 219.99,
      period: " one-time purchase",
      features: [
        "Perpetual license for the current version",
        "8 GB vRAM",
        "4 vCPUs",
        "Run Windows and Windows applications",
        "Use Linux and macOS in a virtual machine",
        "30-days phone and email support",
      ],
    },
    {
      name: "Pro",
      price: 77.99,
      period: "/year",
      features: [
        "128 GB vRAM for each VM",
        "32 vCPUs for each VM",
        "Command line interface",
        "Run graphics-intensive Windows apps and multiple VMs",
        "Develop, automate, test, and debug in multiple operating systems simultaneously",
        "Unlimited phone and email support",
      ],
      highlighted: true,
    },
    {
      name: "Business",
      price: 97.49,
      period: "/year",
      features: [
        "Centralized administration and license management",
        "Automate CI/CD workflows",
        "Provisioning with Mac Management tools or Parallels deployment package",
        "Volume license management for organizations and teams",
        "Business-friendly billing",
        "Allow selected users to download Corporate Windows VM",
      ],
    },
  ],
  features: [
    "Run Windows 11 on Apple silicon Macs",
    "Microsoft-authorized solution for Windows 11 on M-series Macs",
    "Run Windows, Linux, or an additional macOS instance without rebooting",
    "3D acceleration with DirectX and OpenGL",
    "Built-in developer tools and command-line interface",
    "System and performance monitoring",
    "Screen capture and recording",
    "Disk cleanup and memory cleaner",
    "Centralized admin for business teams",
    "Jamf and Intune deployment support",
    "14-day Pro trial",
    "30-day money-back guarantee on direct purchases",
    "24/7 chat support for subscribers",
    "Access to 50+ productivity tools",
  ],
  pros: [
    "Fastest path for Mac users who need Windows apps",
    "Official Microsoft-authorized Windows 11 support on Apple silicon Macs",
    "No reboot workflow makes daily use easy",
    "Strong fit for developers and power users",
    "Business controls are built in for IT teams",
    "Trial lets users test real workflows before paying",
  ],
  cons: [
    "Not free for regular use",
    "Pricing is edition-based and can feel premium",
    "Best experience needs modern Mac hardware",
    "Resource-heavy workloads can tax smaller Macs",
  ],
  useCases: [
    "Running Windows-only business apps on Mac",
    "Testing Windows software on Apple silicon",
    "Development and debugging across operating systems",
    "Gaming tests on a Mac",
    "IT-managed Mac deployments",
    "Office and Excel workflows that need Windows features",
  ],
  quickFacts: [
    "14-day Pro trial",
    "30-day money-back guarantee",
    "24/7 chat support for subscribers",
    "Microsoft-authorized for Windows 11 on Apple silicon Macs",
  ],
} as const;